import type { Metadata } from "next";
import "./globals.css";
import ContentWrapper from "@/components/Layout/ContentWrapper";

export const metadata: Metadata = {
  title: "Demo = SSG + SSR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" m-0">
        <ContentWrapper>{children}</ContentWrapper>
      </body>
    </html>
  );
}
